- name: Setup prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Create github local user
  ansible.builtin.user:
    name: github

- name: Create github actions folder
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: github
    group: github

- name: Download github runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
    dest: /actions-runner
    owner: github
    group: github
    remote_src: yes

- name: Configure github runner
  ansible.builtin.shell: echo ./config.sh --url https://github.com/raghudevopsb83 --token {{ lookup('community.hashi_vault.hashi_vault', 'secret=infra/data/github-runner:RUNNER_TOKEN token={{ vault_token }} url=http://vault-internal.rdevopsb83.online:8200') }}
  args:
    chdir:  /actions-runner
  become_user: github




